# backend/schemas.py
# API contract between frontend and backend.
# Neither side changes this without telling the other.

from pydantic import BaseModel
from typing import Optional


class ChatRequest(BaseModel):
    session_id:  str            # generated by the frontend (uuid4)
    location:    str            # e.g. "Vienna, Austria" — mandatory
    description: Optional[str] = None  # optional: user style / self-description


class ChatResponse(BaseModel):
    session_id:      str
    answer:          str        # outfit recommendation from Claude
    weather_summary: str        # e.g. "12°C, light rain, 60% rain" — shown in UI
    cache_hit:       bool       # frontend can show a small cache indicator